# fly.toml app configuration file generated for bun-cdl on 2023-09-12T15:21:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bun-cdl"
primary_region = "bos"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
